### ISSUE TITLE
`meteor create --package my:package` fails

### ISSUE THREAD

**Issue by maxkfranz** [percolatestudio/atmosphere#367]
```
npm install -g meteor
meteor create --package maxkfranz:cytoscape
```

Result:

```
$ meteor create --package maxkfranz:cytoscape

fs.js:665
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/meteor/examples'
    at Object.fs.readdirSync (fs.js:665:18)
    at Object.Commands.push.func (/usr/local/lib/node_modules/meteor/app/meteor/meteor.js:156:32)
    at main (/usr/local/lib/node_modules/meteor/app/meteor/meteor.js:631:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor/app/meteor/meteor.js:634:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

```
$ meteor --version
Meteor version 0.5.2
```

**Comment by maxkfranz** [comment]
Your `.npmignore` is the problem...

```
macpro14:meteor maxfranz$ cd /usr/local/lib/node_modules/meteor/
macpro14:meteor maxfranz$ ls -al
total 224
drwxr-xr-x  15 maxfranz  staff    510 13 Apr 11:49 .
drwxrwxrwx  28 24561     wheel    952 13 Apr 11:44 ..
-rw-r--r--   1 maxfranz  staff    122 29 Nov  2012 .arcconfig
-rw-r--r--   1 maxfranz  staff     18 29 Nov  2012 .npmignore
-rw-r--r--   1 maxfranz  staff  15895 29 Nov  2012 History.md
-rw-r--r--   1 maxfranz  staff  72315 29 Nov  2012 LICENSE.txt
-rw-r--r--   1 maxfranz  staff   2217 29 Nov  2012 README.md
drwxr-xr-x  13 maxfranz  staff    442 13 Apr 11:44 admin
drwxr-xr-x   5 maxfranz  staff    170 13 Apr 11:44 app
drwxr-xr-x   3 maxfranz  staff    102 29 Nov  2012 dev_bundle
drwxr-xr-x   5 maxfranz  staff    170 13 Apr 11:44 docs
-rwxr-xr-x   1 maxfranz  staff   1023 29 Nov  2012 install.sh
-rwxr-xr-x   1 maxfranz  staff   3336 29 Nov  2012 meteor
drwxr-xr-x  26 maxfranz  staff    884 13 Apr 11:44 node_modules
-rw-r--r--   1 maxfranz  staff   3682 13 Apr 11:44 package.json
macpro14:meteor maxfranz$ cat .npmignore 
packages
examples
macpro14:meteor maxfranz$ 
```

**Comment by maxkfranz** [comment]
Never mind.  It looks like you don't support npm

**Comment by dburles** [comment]
@maxkfranz see https://www.meteor.com/install on how to correctly install Meteor

**Comment by maxkfranz** [comment]
Ya, thanks.  I automatically assumed you'd use npm, since you're also using Node.js for your serverside.  Should have read the docs more...
