### ISSUE TITLE
Error while navigating

### ISSUE THREAD

**Issue by crsssl** [percolatestudio/atmosphere#50]
... which also hurts Iron Router (or whatever you're using). FWIW, here is the console error log:
Exception in setTimeout callback: Error: Can't select in removed DomRange
    at v.$ (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:17158)
    at Object.r.templateInstance.findAll (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21011)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:8023
    at t.extend.withValue (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:1:20096)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:1:16741
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:1:20354

**Comment by zol** [comment]
Thanks, @crsssl are you able to reproduce the problem?

**Comment by crsssl** [comment]
I'll try. It's something surrounding the Search function. I get these errors, too, when clicking the "suggested" searches.

Exception from Deps recompute: TypeError: Object #<Object> has no method 'contributors'
    at Object.Template.packagesShow.helpers.userListData (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17657)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Object #<Object> has no method 'related'
    at Object.Template.packagesShow.helpers.relatedPackages (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17722)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at Object.e.dot (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:12:11266)
    at Spacebars.include.data (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:13:32001)
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Cannot read property 'name' of undefined
    at Object.Template.packagesShow.helpers.versionAndMilestones (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:18188)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Object #<Object> has no method 'related'
    at Object.Template.packagesShow.helpers.relatedPackages (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17722)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Object #<Object> has no method 'dailyScores'
    at Object.Template.packagesShow.helpers.graphSeries (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17531)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Object #<Object> has no method 'contributors'
    at Object.Template.packagesShow.helpers.userListData (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17657)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819) d83cf28cbc7252ae21204ab357923d3029873e06.js:1
Exception from Deps recompute: TypeError: Object #<Object> has no method 'related'
    at Object.Template.packagesShow.helpers.relatedPackages (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:14:17722)
    at http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:26979
    at Object.e.dot (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:12:11266)
    at Spacebars.include.data (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:13:32001)
    at null._func (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:9:21479)
    at n.extend._compute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:4909)
    at n.extend._recompute (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5026)
    at n.extend.flush (http://beta.atmospherejs.com/d83cf28cbc7252ae21204ab357923d3029873e06.js:2:5819)

**Comment by crsssl** [comment]
Try this, and see if you get the same problem...

1) Click on Search Packages now.
2) Choose "Popular Search" = Facebook-sdk
3) Click the Back button.
I believe the problems begin here. Methods "dailyScores", "contributors", "related" and property "name" cannot be found on whatever object they're attached to.

**Comment by zol** [comment]
Awesome, thanks. I was able to reproduce it. Clicking through to a package from the popular searches page then clicking back yields the missing properties errors.

**Comment by crsssl** [comment]
Great. Thanks for all this, and keep up the great work.

**Comment by zol** [comment]
And thank you to you for taking the time out of your day to help us out!

**Comment by tmeasday** [comment]
This is a problem with the cmather branch of IR that hopefully will never make it into real release of IR :) Thanks for the great report @crsssl

**Comment by tmeasday** [comment]
Moving down the stack as I think we can live with it until @cmather hunts down the solution.

**Comment by tmeasday** [comment]
I think this has been fixed.
