### ISSUE TITLE
I was searching and got this error 'options need $regex'

### ISSUE THREAD

**Issue by Tarang** [percolatestudio/atmosphere#91]
Full text of error below (as at time of this issue)

```
Exception from Deps recompute function: Error: $options needs a $regex
    at Error (native)
    at Object.k.$options (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:7630)
    at http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:6375
    at Function.T.each.T.forEach (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:1:1012)
    at g (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:6134)
    at d (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:5493)
    at http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:5349
    at Function.T.each.T.forEach (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:1:1012)
    at r (http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:5135)
    at http://beta.atmospherejs.com/e4ea7b7e564e7afb2c6d5db0fd4f6344304f14c4.js:3:6766 
```

**Comment by tmeasday** [comment]
I could reproduce this by searching for "$foo"

**Comment by tmeasday** [comment]
Hmm.. Not seeing this any more. @Tarangp - can you reproduce?

**Comment by tmeasday** [comment]
ping @Tarangp :)

**Comment by Tarang** [comment]
@tmeasday yup looks like this one is fixed! The SSL is also making it really fast now! =)
